### PR TITLE
fix: move block caching out of static initializer

### LINKED ISSUE #205: Game crashes when configuring the world through the universe setup.
When trying to configure the world through the universe setup screen, the game crashes and throws a ```ExceptionInInitializerError``` due to a ```NullPointerException``` when trying to retrieve a block for ```LightAndShadowResources:redDice```.

```18:54:53.117 [main] ERROR o.t.a.m.ModuleAwareAssetTypeManager - No asset type available for asset producer class org.terasology.tintOverlay.TintOverlayTextureProducer
18:54:53.117 [main] ERROR o.t.a.m.ModuleAwareAssetTypeManager - No asset type available for asset producer class org.terasology.engine.rendering.iconmesh.IconMeshDataProducer
18:55:00.935 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (34716), capping to 1000
18:55:07.987 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.terasology.reflection.reflect.ReflectionReflectFactory$ReflectionConstructor.construct(ReflectionReflectFactory.java:78)
	at org.terasology.reflection.metadata.ClassMetadata.newInstance(ClassMetadata.java:191)
	at org.terasology.engine.world.generator.plugin.DefaultWorldGeneratorPluginLibrary.instantiateAllOfType(DefaultWorldGeneratorPluginLibrary.java:37)
	at org.terasology.engine.world.generation.WorldBuilder.addPlugins(WorldBuilder.java:67)
	at org.terasology.las.LaSSimpleWorldGenerator.createWorld(LaSSimpleWorldGenerator.java:65)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getConfigurator(BaseFacetedWorldGenerator.java:74)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.configureProperties(WorldSetupScreen.java:157)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.setWorld(WorldSetupScreen.java:141)
	at org.terasology.engine.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$1(UniverseSetupScreen.java:180)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
	at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:673)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:389)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:268)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:247)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.engine.input.InputSystem.send(InputSystem.java:525)
	at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:497)
	at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
	at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
	at org.terasology.engine.core.modes.StateMainMenu.handleInput(StateMainMenu.java:195)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:506)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:460)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:436)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:402)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
Caused by: java.lang.NullPointerException: null
	at org.terasology.las.platform.FloatingPlatformRasterizer.<clinit>(FloatingPlatformRasterizer.java:33)
	... 40 common frames omitted
18:55:07.987 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...```

### PR DESCRIPTION
**Pull request by naalit**
This moves getting red and black dice blocks from the BlockManager to the `initialize()` method of the rasterizer instead of having them in static constructors. Alongside https://github.com/Terasology/CoreWorlds/pull/39, it should fix the world setup and preview screens in LaS.

### CODE REVIEW

File: src/main/java/org/terasology/las/platform/FloatingPlatformRasterizer.java [hunk 1]
```diff
@@ -30,12 +30,14 @@
 public class FloatingPlatformRasterizer implements WorldRasterizerPlugin {
 
     private BlockTheme theme;
-    private static final Block RED_DICE = CoreRegistry.get(BlockManager.class).getBlock("LightAndShadowResources:redDice");
-    private static final Block BLACK_DICE = CoreRegistry.get(BlockManager.class).getBlock("LightAndShadowResources:blackDice");
+    private Block redDice;
+    private Block blackDice;
```
Comment (naalit) [inline src/main/java/org/terasology/las/platform/FloatingPlatformRasterizer.java:34]: Is there any reason these were `static` before? I just made them instance variables, since they're initialized with the other instance variables, and there's only ever one instance of the rasterizer anyway.

**Review by ahv15 — APPROVED** [review]

File: src/main/java/org/terasology/las/platform/FloatingPlatformRasterizer.java (hunk 1 above)
Comment (skaldarnar) [reply src/main/java/org/terasology/las/platform/FloatingPlatformRasterizer.java:34]: I don't think so. Probably was a checkstyle fix or something like that that we did without looking in too much detail.

**Review by skaldarnar — APPROVED** [review]
