### PR TITLE
Remove previous scores after restarting game

### LINKED ISSUE #151: Player names multiply at the ending screen after restarting the game
## Issue

The previously placed names at the game over screen are not removed when you restart and finish the game, thus the names keep multiplying.

## How to reproduce

1. Start a LAS Game (it can be single-player too)
2. Complete the game
3. Restart the game by clicking the "Restart" button on the screen
4. Repeat at least one more time the steps 2. and 3.
5. You will notice the names to repeat themselves with each completion of the game

## Screenshot

image

### PR DESCRIPTION
**Pull request by ahv15**
### Contains
"Fixes #151"
The screen with the players and scores from the previously played games are reset when the game is restarted.

### How to test
Complete a game once and then restart the game and complete it once again.

### Outstanding before merging
- [x] Previous game scores do not persist

### CODE REVIEW

**Comment by ahv15** [comment]
Regarding this issue should I keep track of the players kills and death for the entire duration the player is playing or just for each restarted game?

**Comment by ahv15** [comment]
Currently the players stats are not reset after every game.

**Comment by stefaniamak** [comment]
> 
> 
> Regarding this issue should I keep track of the players kills and death for the entire duration the player is playing or just for each restarted game?

In my opinion, I would suggest to reset the K/D 🤔 considering the stats represent each round!

**Comment by ahv15** [comment]
Made the change so now the kills and deaths are stored for each game.

**Comment by ahv15** [comment]
Cant seem to figure out what went wrong with this, everything seemed fine while testing it and the errors dont seem related to this commit either maybe the error lies elsewhere?

**Comment by Cervator** [comment]
Heya @ahv15 - just looks like our Artifactory crashed for a bit, meaning all builds would fail. Fixed now and I tried rerunning the build for this :-)

**Comment by ahv15** [comment]
thanks @Cervator  but it still looks like there is a slight error in here.

**Comment by Cervator** [comment]
@ahv15 might just be the way I triggered the rebuild didn't fully refresh the commit status checks here. If you click through to the broken build listed by that one commit status you'll see there's a newer one which worked fine :-)

http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/L/job/LightAndShadow/job/PR-159/5/

So as far as build status you're good on this PR, all is well 👍

File: src/main/java/org/terasology/ligthandshadow/componentsystem/components/PlayerStatisticsComponent.java [hunk 1]
```diff
@@ -34,4 +34,12 @@ public  PlayerStatisticsComponent() {
         this.kills = 0;
         this.deaths = 0;
     }
+
+    public void setKills(int kills) {
```
Comment (Cervator) [inline src/main/java/org/terasology/ligthandshadow/componentsystem/components/PlayerStatisticsComponent.java]: You generally do not need setters or getters in components, since the fields tend to be public you normally just set them directly :-)

File: src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java [hunk 2]
```diff
@@ -92,6 +92,8 @@ public void onGameOver(GameOverEvent event, EntityRef entity) {
     private void addPlayerStatisticsInfo(DeathScreen deathScreen, GameOverEvent event) {
         MigLayout spadesTeamMigLayout = deathScreen.find("spadesTeamPlayerStatistics", MigLayout.class);
         MigLayout heartsTeamMigLayout = deathScreen.find("heartsTeamPlayerStatistics", MigLayout.class);
+	spadesTeamMigLayout.removeAllWidgets();
```
Comment (Cervator) [inline src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java:95]: Uh oh watch out! A tab character! 😱 

Protip: Make sure your IDE has the Checkstyle plugin installed and with the Terasology rules active. See https://github.com/MovingBlocks/Terasology/wiki/Checkstyle for details

Then just habitually check files you've modified in the IDE and it'll catch issues like this :-)

**Review by Cervator — CHANGES_REQUESTED** [review]
Other than some trivial code style fixes this seems good, can confirm the second game over looked clean 👍

File: src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java (hunk 2 above)
Comment (ahv15) [reply src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java:95]: yeah I was going to add this but forgot about it :grin:

Comment (ahv15) [reply src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java:95]: Screenshot (394)
I wonder where that tab character sneaked in from, it looks fine when I view the file

Comment (ahv15) [reply src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/ClientGameOverSystem.java:95]: Checkstyle verified that there was no style errors in this file at least :relieved:

File: src/main/java/org/terasology/ligthandshadow/componentsystem/components/PlayerStatisticsComponent.java (hunk 1 above)
Comment (ahv15) [reply src/main/java/org/terasology/ligthandshadow/componentsystem/components/PlayerStatisticsComponent.java]: ok

**Review by Cervator — APPROVED** [review]
Tested it out and can confirm it seemed to reset scores between rounds 🎉 

Still saw a few of the style issues outstanding, wonder if your Checkstyle isn't set up right @ahv15 ?

In any case the changes were trivial and this would be good for a play test very soon ™️ so I just made them myself real quick while merging :-)

Thanks!

**Comment by Cervator** [comment]
Remaining style tweaks were done with https://github.com/Terasology/LightAndShadow/commit/5cb1bf3c5f16bc9dfc8126d252cf2d161760b6d8

**Comment by ahv15** [comment]
oops, I really need to watch out for those style issues, seems like I missed out on those tiny issues even though it showed up on checkstyle but I wonder how the tab came in there I was pretty sure there was no problem with that at least.

**Comment by Cervator** [comment]
No idea! Tabs can be sneaky :-)
